### ISSUE TITLE
Add Provider for Soundcloud

### ISSUE THREAD

**Issue by thenonameguy** [stretchr/gomniauth#12]
Hey stretchr!
I'm working a new project that involves interacting with the SoundCloud API.
I'd be happy to contribute to this awesome library with a provider.

Expect a pull request in a few hours! :smile:

**Comment by mxjxn** [comment]
I'm trying to make use of the soundcloud provider and keep running into the same error trying to authenticate: 
"Error when trying to get user from &{0x18a1c608 0x8806610} - unexpected end of JSON input"

https://github.com/mxjxn/gochat/blob/master/auth.go

Looking for a bit of advice or a point in the right direction
